config/routes.rb
Shopen::Application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    devise_for :users, :skip => [:registrations]
    devise_scope :user do
      resource :registration, only: [:new, :create], path: 'users', controller: 'devise/registrations', as: :user_registration
    end
    
    namespace :admin do 
      resources :products
      root to: 'products#index'
    end
    resource :user
    resources :categories
    resources :products, only: [:index, :show]
    get '/:locale' => 'products#index'
  end

  root to: 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category, :counter_cache => true
  
  has_many :photos
  has_many :reviews
  has_many :discounts

  monetize :base_price_kopeks
  monetize :discount_price_kopeks

  def has_discount?
    discounts.active.any?
  end

  def has_photos?
    photos.any?
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :load_products

  def index
    @products = @products.order(:name)
    @products = @products.page(params[:page]).per(params[:per])
  end

  def show 
    @product = @products.find(params[:id])
    @discounts = @product.discounts
  end

  def new
    @categories = Category.all
    @product = @products.build
  end

  def create
    @categories = Category.all
    @product = @products.build(product_params)
    if @product.save
      redirect_to admin_product_path(@product), flash: { notice: t('admin.products.create.success') }
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    @product = @products.find(params[:id])
  end

  def update
    @categories = Category.all
    @product = @products.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product), flash: { notice: t('admin.products.update.success') }
    else
      render :edit
    end
  end

  private

  def product_params
    fields = [:name, :description, :base_price, :category_id]
    params.require(:product).permit(*fields)
  end

  def load_products
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_products

  RELATED_PRODUCTS_COUNT = 10

  def index
    params[:view_mode] ||= 'grid'
    @products = @products.order(:name)
    @products = @products.page(params[:page]).per(params[:per])
  end
  
  def show
    @related_products = Product.all.limit(RELATED_PRODUCTS_COUNT)
    @product = @products.find(params[:id])
    @photos = @product.photos
    @reviews = @product.reviews
  end

  private

  def load_products
    @products = Product.all
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  DEFAULT_IMAGE_OPTIONS = { :size => :small }

  def product_image(product, options = DEFAULT_IMAGE_OPTIONS)
    content_tag(:a, content_tag(:img, nil, src: image_url("product-l1.jpg")), href: product_path(product))      
  end

  def product_sale_ribbon(product)
    content_tag(:span, "Sale", class: 'sale')
  end

  def product_price(product)
    if product.has_discount?
      [
        content_tag(:span, humanized_money_with_symbol(product.base_price), class: 'oldprice'), 
        content_tag(:span, humanized_money_with_symbol(product.discount_price), class: 'newprice')
      ].join('\n')
    else
      content_tag(:span, humanized_money_with_symbol(product.base_price), class: 'newprice')
    end
  end
end

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, product], html: {class: 'form-horizontal' } do |f|
  .row
    .span8
      = form_fieldset_header t('.required_info_title'), t('.required_info_description')
      %fieldset
        = f.input :name, input_html: {class: 'input-xlarge'}
        = f.input :base_price, as: :money, input_html: {class: 'input-xlarge'}
        = f.association :category, collection: categories, input_html: {class: 'input-xlarge'}
      = form_fieldset_header t('.additional_details_title'), t('.additional_details_description')
      %fieldset
        = f.input :description, input_html: {class: 'input-xxlarge', rows: text_area_rows_count}
    .span4
      = render partial: 'admin/products/photos'
  .row.form-actions
    = f.button :submit, t('.submit'), class: ['btn-success']

app/views/admin/products/_photos.html.haml
%img{src: image_path('product1.jpg')}
%a{href: '#', id: 'add-product-photo-link'}= t('.add_photo')

app/views/admin/products/edit.html.haml
.container
  = main_page_header t('.page_header')
  = render partial: 'admin/products/form', locals: {product: @product, categories: @categories}

app/views/admin/products/index.html.haml
.container  
  .btn-toolbar
    %a.btn.btn-success{href: new_admin_product_path}= t('.new')
    .pull-right
      = render partial: 'admin/shared/search'

  = render partial: 'products/list', locals: { products: @products, admin: true }
  
  .pull-right
    = paginate @products

app/views/admin/products/new.html.haml
.container
  = main_page_header t('.page_header')
  = render partial: 'admin/products/form', locals: {product: @product, categories: @categories}

app/views/admin/products/show.html.haml
.container
  = breadcrumb [t('site.sections.admin'), admin_root_path], [t('site.sections.products'), admin_products_path], @product.name
  = main_page_header t('.page_header')
  = tabs 'presentation-tabs' do |t|
    = t.tab 'info', t('.info_tab_title'), active: true do
      = render partial: 'admin/products/info', locals: {product: @product}
    = t.tab 'discounts', t('.discounts_tab_title') do
      = render partial: 'admin/products/discounts', locals: {product: @product}