config/routes.rb
Shopen::Application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    devise_for :users, :skip => [:registrations]
    devise_scope :user do
      resource :registration, only: [:new, :create], path: 'users', controller: 'devise/registrations', as: :user_registration
    end
    
    namespace :admin do 
      resources :products
      root to: 'products#index'
    end
    resource :user
    resources :categories
    resources :products, only: [:index, :show]
    get '/:locale' => 'products#index'
  end

  root to: 'products#index'
end

app/views/shared/navbar/_cart.html.haml
%li.dropdown.hover.topcart
  %a.dropdown-toggle{href: "#", data: {toggle: "dropdown"}}
    %i.carticon
    Shopping Cart 
    %span.label.label-success.font14= "1 item(s)"
    = "- $589.50"
    %b.caret
  %ul.dropdown-menu.topcartopen
    %li
      = render partial: 'shared/navbar/cart/items'
      = render partial: 'shared/navbar/cart/summary'
      = render partial: 'shared/navbar/cart/actions'

          

app/views/shared/navbar/_language.html.haml
%li.dropdown
  %a.dropdown-toggle{href: "#", data: {toggle: "dropdown"}}
    = t("languages.#{current_language}")
    %b.caret
  %ul.dropdown-menu
    %li
      %a{href: url_for(locale: 'en')}= t('languages.en')
    %li
      %a{href: url_for(locale: 'ru')}= t('languages.ru')

app/views/shared/navbar/_main.html.haml
#main-nav.navbar.navbar-fixed-top
  .container
    %button{class: "btn btn-navbar", type: "button", data: {target: ".nav-collapse", toggle: "collapse"}}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    
    = render partial: 'shared/navbar/menu'
    %ul#navbar-right.nav.pull-right
      = render partial: 'shared/navbar/language'
    
    
          
            

app/views/shared/navbar/_menu.html.haml
%nav.nav-collapse.collapse
  %ul.nav
    %li
      = link_to t('.home'), root_path
    - if user_signed_in?
      %li
        = link_to t('.account'), user_path
      %li
        = link_to t('.shop'), admin_root_path
      %li
        = link_to t('.sign_out'), destroy_user_session_path, :method => :delete
    - else
      %li
        = link_to t('.sign_in'), new_user_session_path
      %li
        = link_to t('.sign_up'), new_user_registration_path